$args = @(
  "train.py",
  "--data","./data.yaml",
  "--model","yolo26l.pt",
  "--imgsz","1024",
  "--epochs","300",
  "--device","0",
  "--batch","10",
  "--workers","10",
  "--cache","disk",
  "--optimizer","AdamW",
  "--cos_lr","true",
  "--lr0","0.003",
  "--lrf","0.01",
  "--weight_decay","0.01",
  "--warmup_epochs","3",
  "--close_mosaic","10",
  "--mosaic","1.0",
  "--mixup","0.10",
  "--copy_paste","0.05",
  "--degrees","8",
  "--translate","0.10",
  "--scale","0.50",
  "--fliplr","0.50",
  "--hsv_h","0.015",
  "--hsv_s","0.70",
  "--hsv_v","0.40",
  "--erasing","0.10",
  "--amp","true",
  "--compile","false",
  "--matmul","highest",
  "--project","runs/fuel",
  "--name","4080s_yolo26l_1024_b24_adamw"
)

python @args